name: Reusable Build

on:
  workflow_call:
    inputs:
      path_env:
        required: true
        type: string
      environment:
         required: true
         type: string
    secrets:
      PROPERTIES_REPO_TOKEN:
        required: true
    outputs:
      version:
        description: "The version from package.json"
        value: ${{ jobs.build.outputs.version }}

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    steps:
      - uses: actions/checkout@v4

      - name: Checkout properties repo
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/japl-properties
          token: ${{ secrets.PROPERTIES_REPO_TOKEN }}
          path: japl-properties
          sparse-checkout: |
            ${{ inputs.path_env }}
          sparse-checkout-cone-mode: false
          
      - name: Copy environment file
        run: |
          ENV_PATH=$(echo "${{ inputs.path_env }}" | sed 's|^\./||')
          mv "japl-properties/$ENV_PATH" src/environments/environment.ts
          rm -rf japl-properties
          pwd
          ls src

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Get version
        id: get_version
        run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: dist/ur_admin_site
