name: Reusable Tag

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Create and push tag
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          TAG_NAME="v${{ inputs.version }}-${{ github.run_number }}"
          git tag $TAG_NAME
          git push origin $TAG_NAME
